
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'app.dart';
import 'core/storage/hive_adapters.dart';
import 'core/storage/hive_service.dart';
// Hive model adapters (auto-generated)
import 'features/whiteboard/data/models/stroke_model.dart';
import 'features/whiteboard/data/models/slide_model.dart';
import 'features/whiteboard/data/models/canvas_object_model.dart';
import 'features/whiteboard/data/models/slide_annotation.dart';
import 'features/whiteboard/data/models/session_model.dart';
import 'features/question_widget/data/models/question_widget_model.dart';
import 'features/question_widget/data/models/question_widget_style.dart';
import 'features/question_widget/data/models/set_layout_models.dart';
import 'features/whiteboard/data/models/page_models.dart';


void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Hive.initFlutter();

  // ══════════════════════════════════════════════════════════════════════════╗
  // CRITICAL: Register adapters in EXACT order per PRD (typeId order matters) ║
  // Generated by build_runner code generation                                 ║
  // ══════════════════════════════════════════════════════════════════════════╝
  
  // Register Hive adapters in typeId order (1–11, then 20)
  // These are auto-generated by hive_generator from model source files
  Hive.registerAdapter(SetSlideModelAdapter());      // typeId: 1
  Hive.registerAdapter(SlideOptionAdapter());        // typeId: 2
  Hive.registerAdapter(StrokeModelAdapter());        // typeId: 3
  Hive.registerAdapter(CanvasObjectModelAdapter());  // typeId: 4
  Hive.registerAdapter(SlideAnnotationDataAdapter());// typeId: 5
  Hive.registerAdapter(SlideColorConfigAdapter());   // typeId: 6
  Hive.registerAdapter(WhiteboardSessionModelAdapter());// typeId: 7
  Hive.registerAdapter(ObjectTypeAdapter());         // typeId: 8
  Hive.registerAdapter(StrokeTypeAdapter());         // typeId: 9
  Hive.registerAdapter(QuestionWidgetModelAdapter());     // typeId: 10
  Hive.registerAdapter(QuestionWidgetStyleAdapter());     // typeId: 11
  Hive.registerAdapter(OffsetAdapter());             // typeId: 20 (custom)
  Hive.registerAdapter(BaseWidgetLayoutAdapter());   // typeId: 21
  Hive.registerAdapter(QuestionLayoutAdapter());     // typeId: 22
  Hive.registerAdapter(OptionsLayoutAdapter());      // typeId: 23
  Hive.registerAdapter(SetSettingsModelAdapter());   // typeId: 24
  Hive.registerAdapter(PageTypeAdapter());           // typeId: 25
  Hive.registerAdapter(SetImportPageAdapter());      // typeId: 27
  Hive.registerAdapter(BlankPageAdapter());          // typeId: 28


  // Initialize all Hive boxes
  await HiveService.init();

  runApp(const ProviderScope(child: EduBoardApp()));
}
